plugins {
    id 'ru.axenix.smartax.plugin.openapi-configurator-plugin' version "${CONFIGURATOR_PLUGIN_VERSION}"
}

dependencies {
    implementation platform(external.spring.boot.bom)
    api project(':dui-service-contract')

    api external.spring.boot.starter.webflux
    api external.spring.boot.autoconfigure

    annotationProcessor external.lombok
    annotationProcessor external.spring.boot.configuration.proccessor

    compileOnly external.lombok

    testRuntimeOnly external.junit.platform.launcher

    testImplementation internal.test.commons
    testImplementation external.spring.boot.starter.test
}