plugins {
    id 'ru.axenix.smartax.plugin.library-configurator-plugin' version "${CONFIGURATOR_PLUGIN_VERSION}"
}

dependencies {
    implementation platform(external.spring.boot.bom)

    implementation external.springdoc.openapi.starter.webmvc.ui
    implementation external.lombok

    annotationProcessor external.lombok
}