plugins {
    id 'ru.axenix.smartax.plugin.openapi-configurator-plugin' version "${CONFIGURATOR_PLUGIN_VERSION}"
}

dependencies {
    implementation platform(external.spring.boot.bom)
    api external.spring.boot.starter.web

    annotationProcessor external.lombok

    compileOnly external.lombok
}