plugins {
    id 'ru.axenix.smartax.plugin.service-configurator-plugin' version "${CONFIGURATOR_PLUGIN_VERSION}"
    id 'ru.axenix.smartax.plugin.liquibase-helper' version "${LIQUIBASE_HELPER_VERSION}"
}

dependencies {
    implementation platform(external.spring.boot.bom)
    implementation project(':dui-service-integration')
    implementation project(':dui-service-contract')

    implementation internal.auth.common
    implementation internal.kafka.group
    implementation internal.logging.common.lib
    implementation internal.service.web
    implementation internal.util

    implementation external.liquibase.core
    implementation external.mapstruct
    implementation external.springdoc.openapi.starter.webmvc.ui
    implementation external.spring.boot.starter.web
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation external.spring.boot.starter.actuator
    implementation external.spring.boot.starter.data.jpa
    implementation external.spring.boot.starter.validation
    implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc:1.0.3'
    implementation 'net.minidev:json-smart:2.4.9'

    runtimeOnly external.postgresql

    compileOnly external.lombok

    annotationProcessor external.lombok
    annotationProcessor external.mapstruct.processor

    testImplementation internal.test.commons
    testImplementation external.spring.boot.starter.test
    testImplementation external.embedded.database.spring.test
    testImplementation external.embedded.postgres

}

tasks.named('processResources') {
    from("$rootDir/docs") {
        include 'template/**'
    }
}


