plugins {
    id 'ru.axenix.smartax.plugin.library-configurator-plugin' version "${CONFIGURATOR_PLUGIN_VERSION}"
}

dependencies {
    implementation platform(external.spring.boot.bom)
    api project(':dui-service-model')

    api internal.print.service.client

    implementation internal.logging.common.lib
    implementation internal.service.web

    implementation external.commons.lang3
    implementation external.mapstruct
    implementation external.springdoc.openapi.starter.webmvc.ui
    implementation external.spring.boot.starter.web
    implementation external.spring.boot.starter.actuator
    implementation external.spring.boot.starter.validation
    implementation external.json.smart

    compileOnly external.lombok

    annotationProcessor platform(external.spring.boot.bom)
    annotationProcessor external.lombok
    annotationProcessor external.mapstruct.processor

    testImplementation internal.test.commons
    testImplementation external.spring.boot.starter.test

    testRuntimeOnly external.junit.platform.launcher
}
